### ISSUE TITLE
array indexing

### ISSUE THREAD

**Issue by krs-world** [BridgesUNCC/bridges-cxx#70] opened 2018-08-15 15:00 UTC
The index order for 2D array (what is displayed in the visualization) seems to be the opposite of what we want. I think row major is more the norm. The first index should be the row (horizontal) and second index should be column.

**Comment by esaule** [comment] 2018-11-01 22:16
This seems like a web browser side problem. @squeetus  ?

**Comment by esaule** [comment] 2018-12-26 18:34
The java version does the indexing for 2D is a strange way. The 2d access in java are strange: setElement and getElement are using different indexing.
```	public Element<E> getElement(int x, int y) {
		return array_data[y * dims[1] + x];
	}
	public void setElement(int x, int y, Element<E> el) {
		array_data[y * dims[0] + x] = el;
	}
```
I guess it is a bug in the java version, but I'll let @krs-world decide what to do.

The code is built so that in the JSON, (x=0,y=0) comes first and (x=1,y=0) comes second which makes sense graphically. But when building a for loop, you usually would write
```for (int i; i<nbline;++i)
    for (int j=0; j<nbcol;++j)
        myarray[i][j] = something();```
but substitution i by x, and j by y get the reverse semantic. I wonder if that is what is going on.
@krs-world @squeetus opinions?

**Comment by esaule** [comment] 2018-12-27 23:32
je java weirdness is fixed upstream.

**Comment by squeetus** [comment] 2019-01-04 01:00
Is this fixed now, or do we need to tweak the array visualization code?

**Comment by esaule** [comment] 2019-01-04 01:34
There is no need to tweak the visualization code at this point. I
believe the issue is a convention issue on the client side.

The clients documentation specify set(a,b) with x=a and y=b. While
there is nothing wrong with that, I think most people would understand
set(a,b) as row=a and column=b. That is what you expect out of your
typical nexted (i,j) loops. But the client is specified x,y and the
visualization is consistent with that.

So this is not really a bug in the sense that it is consistent. But we
may want to rewrite the clients to use row/column. Let's do this next
semester.

**Comment by esaule** [comment] 2019-07-30 19:37
done.

**Closed by esaule** 2019-07-30 19:37 UTC
