### ISSUE TITLE
Shapes and Symbol classes  updated..

### ISSUE THREAD

**Issue by krs-world** [BridgesUNCC/bridges-cxx#79] opened 2018-12-24 16:04 UTC
I have worked on these classes and now we have a cleaner hierarchy:

Symbol is the parent abstract class of the Symbol hierarchy and 
Rectangle
Circle
Polygon (should be renamed polyline, actually)
Label

are subclasses. Symbol still contains the non-geometric attributes, and might need to be pushed to the subclasses, if they are not all required for each subclass.   The JSON is constructed in each of the subclasses, with the non-geometric part of it coming from Symbol.

To do:
1. Need additional pair of eyes to bullet proof it.
2. static member for ids need to be removed by pushing to a function (Erik's solution)
3. (2) reminds me that we were doing something like that in Element - need to check.
4. Need to update  the Java version (any volunteers?) to be consistent.
5. Need to update/do the Python version (Matthew).

Have added a C++ test to the shape collection and will push that.

**Comment by esaule** [comment] 2018-12-26 18:09
Symbol::getIdentifier does something strange. It returns a new identifier every time it is called. Is that the intended behavior?
Shouldn't a particular shape have the same identifier if getIdentifier is called twice? What is this identifier needed for?

**Comment by krs-world** [comment] 2018-12-26 20:53
I think David implemented this to keep track of each symbol. It should be incrementing monotonically as each symbol is created. I have to check, thats what I recall. We used to do something like that for Element.

**Comment by esaule** [comment] 2018-12-27 23:34
The static id in the symbol collection should be fixed sometimes.
But I expect @squeetus to push the update on the server before the beginning of the semester.

**Comment by esaule** [comment] 2022-08-07 01:25
this is no longer an issue since we refactored shapecollection a couple years ago

**Closed by esaule** 2022-08-07 01:25 UTC
